#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[[kv_namespaces]]
binding = "CUSTOM_PROVIDERS_KV"
id = "REPLACE_WITH_CUSTOM_PROVIDERS_KV_ID"
preview_id = "REPLACE_WITH_CUSTOM_PROVIDERS_KV_PREVIEW_ID"

[triggers]
crons = ["0 0 * * *"]
